class Events {
    WELCOME_PAGE_SPACE_PRESS = 'WELCOME_PAGE_SPACE_PRESS'
    SPAWN_A_BULLET = 'SPAWN_A_BULLET'
    BULLET_REACHED_A_WALL = 'BULLET_REACHED_A_WALL'
    COLLISION_DETECTED = 'COLLISION_DETECTED'
}

const events = new Events;

export default events;