class Events {
    SPACE_PRESSED_FOR_GAME_START = 'SPACE_PRESSED_FOR_GAME_START'
    SPAWN_A_BULLET = 'SPAWN_A_BULLET'
    BULLET_REACHED_A_WALL = 'BULLET_REACHED_A_WALL'
    COLLISION_DETECTED = 'COLLISION_DETECTED'
    ALL_LIVES_LOST = 'ALL_LIVES_LOST'
}

const events = new Events;

export default events;